# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsHumedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsLuminosidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsValvula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Maceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDePlantacion', models.DateTimeField()),
                ('primeraCosecha', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.User')),
            ],
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='maceta',
            name='tipoPlanta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maceta.Plantas'),
        ),
        migrations.AddField(
            model_name='logsvalvula',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maceta.Maceta'),
        ),
        migrations.AddField(
            model_name='logstemperatura',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maceta.Maceta'),
        ),
        migrations.AddField(
            model_name='logsluminosidad',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maceta.Maceta'),
        ),
        migrations.AddField(
            model_name='logshumedad',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maceta.Maceta'),
        ),
    ]
